// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package orm

import (
	"gorm.io/gorm"
	"linkweek-go/config"
)

// Injectors from injector.go:

func Build() *gorm.DB {
	configConfig := config.Provider()
	db := Provider(configConfig)
	return db
}
