// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package legacy

import (
	"database/sql"
	"linkweek-go/config"
)

// Injectors from injector.go:

func Build() *sql.DB {
	configConfig := config.Provider()
	db := Provider(configConfig)
	return db
}
